language: python
sudo: required
dist: xenial
python: "3.7"

addons:
  firefox: "latest"

before_install:
  - make webdriver

install:
  - make deps

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - make unittest
  - make functest