language: python
sudo: required
dist: xenial
python: "3.7"

addons:
  firefox: "latest"

before_install:
  # Get webdriver for selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - make deps

script:
  - make unittest
  - PATH=$PATH:$PWD/geckodriver pytest chapter01/mysite/blog/tests/functional --driver Firefox