language: python
sudo: required
dist: xenial
python: "3.7"

addons:
  firefox: "latest"

before_install:
  # Get webdriver for selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - tar -xzf geckodriver*.tar.gz
  - rm geckodriver*.tar.gz

install:
  - make deps

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - make unittest
  - pytest --driver Firefox --driver-path $PWD/geckodriver chapter01/mysite/blog/tests/functional