language: python
sudo: required
dist: xenial
python: "3.7"

addons:
  firefox: "latest"

before_install:
  # Get webdriver for selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - pwd
  - ls geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - make deps

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - make unittest
  - echo $PATH
  - pwd
  - pytest chapter01/mysite/blog/tests/functional --driver Firefox --driver-path ~/geckodriver/geckodriver