language: python
sudo: required
dist: xenial
python: "3.7"

install:
  - pip install -r requirements.txt

script:
  - pytest chapter01/mysite/blog/tests/unit
  - pytest chapter01/mysite/blog/tests/functional